products:
- name: Pink_donut
  start_value: 3
  required_amount: 4
  shelf_sort_number: 1
  restock_sort_number: 14
  daily_use: 0
- name: Sprinkled_donut_kakao
  start_value: 3
  required_amount: 4
  shelf_sort_number: 2
  restock_sort_number: 16
  daily_use: 0
- name: Confetii_donut
  start_value: 3
  required_amount: 4
  shelf_sort_number: 3
  restock_sort_number: 12
  daily_use: 0
- name: Hoj_snegl
  start_value: 4
  required_amount: 8
  shelf_sort_number: 4
  restock_sort_number: 9
  daily_use: 1
- name: KBH_birkes
  start_value: 5
  required_amount: 8
  shelf_sort_number: 5
  restock_sort_number: 20
  daily_use: 0
- name: Birkes
  start_value: 3
  required_amount: 4
  shelf_sort_number: 6
  restock_sort_number: 17
  daily_use: 0
- name: Grovbirkes
  start_value: 3
  required_amount: 4
  shelf_sort_number: 7
  restock_sort_number: 18
  daily_use: 0
- name: Polsehorn_med_ketchup
  start_value: 4
  required_amount: 4
  shelf_sort_number: 8
  restock_sort_number: 26
  daily_use: 0
- name: Smo_polsehorn
  start_value: 4
  required_amount: 4
  shelf_sort_number: 9
  restock_sort_number: 4
  daily_use: 0
- name: Polsehorn_med_kylling
  start_value: 4
  required_amount: 4
  shelf_sort_number: 10
  restock_sort_number: 25
  daily_use: 0
- name: Stang_flodeost_jalapeno
  start_value: 1
  required_amount: 1
  shelf_sort_number: 11
  restock_sort_number: 24
  daily_use: 0
- name: Twist_spinat_feta 
  start_value: 1
  required_amount: 1
  shelf_sort_number: 12
  restock_sort_number: 22
  daily_use: 0
- name: Pizzasnegl
  start_value: 4
  required_amount: 4
  shelf_sort_number: 13
  restock_sort_number: 15
  daily_use: 0
- name: Pizza_pepperoni
  start_value: 3
  required_amount: 3
  shelf_sort_number: 14
  restock_sort_number: 10
  daily_use: 0
- name: Bloddejsstang
  start_value: 3
  required_amount: 3
  shelf_sort_number: 15
  restock_sort_number: 5
  daily_use: 0
- name: Bagte_chokolademuffins
  start_value: 2
  required_amount: 2
  shelf_sort_number: 16
  restock_sort_number: 8
  daily_use: 0
- name: Macaron
  start_value: 3
  required_amount: 3
  shelf_sort_number: 17
  restock_sort_number: 27
  daily_use: 0
- name: Chokolade_croissaint
  start_value: 2
  required_amount: 2
  shelf_sort_number: 18
  restock_sort_number: 29
  daily_use: 0
- name: Kakaocroissaint
  start_value: 3
  required_amount: 3
  shelf_sort_number: 19
  restock_sort_number: 13
  daily_use: 0
- name: Crossaint
  start_value: 4
  required_amount: 4
  shelf_sort_number: 20
  restock_sort_number: 30
  daily_use: 0
- name: Brunsviger_knude
  start_value: 6
  required_amount: 8
  shelf_sort_number: 21
  restock_sort_number: 11
  daily_use: 0
- name: Morgenstang
  start_value: 2
  required_amount: 8
  shelf_sort_number: 22
  restock_sort_number: 28
  daily_use: 2
- name: Kanelstang
  start_value: 5
  required_amount: 8
  shelf_sort_number: 23
  restock_sort_number: 3
  daily_use: 1
- name: Kagemandstang
  start_value: 3
  required_amount: 3
  shelf_sort_number: 24
  restock_sort_number: 6
  daily_use: 0
- name: Kanelsnurre
  start_value: 4
  required_amount: 4
  shelf_sort_number: 25
  restock_sort_number: 19
  daily_use: 0
- name: Snurre_med_remonce
  start_value: 4
  required_amount: 4
  shelf_sort_number: 26
  restock_sort_number: 21
  daily_use: 0
- name: Brunsvigerstang
  start_value: 6
  required_amount: 6
  shelf_sort_number: 27 
  restock_sort_number: 7
  daily_use: 0
- name: Onsdags_snegl
  start_value: 3
  required_amount: 10
  shelf_sort_number: 28
  restock_sort_number: 0
  daily_use: 0
- name: Cremebolle
  start_value: 2
  required_amount: 4
  shelf_sort_number: 29
  restock_sort_number: 23
  daily_use: 0
- name: Skagenshorn
  start_value: 2
  required_amount: 2
  shelf_sort_number: 30
  restock_sort_number: 2
  daily_use: 0
- name: Kernemelkshorn
  start_value: 2
  required_amount: 2
  shelf_sort_number: 31
  restock_sort_number: 1
  daily_use: 0
